import { useState, useEffect } from "react";
import toast from "react-hot-toast";

const TABS = ["Concept", "Materials", "Furniture", "Budget", "Shop"];

function Lightbox({ src, onClose }) {
  useEffect(() => {
    const onKey = (e) => { if (e.key === "Escape") onClose(); };
    document.addEventListener("keydown", onKey);
    return () => document.removeEventListener("keydown", onKey);
  }, [onClose]);

  return (
    <div
      onClick={onClose}
      style={{
        position: "fixed", inset: 0, zIndex: 1000,
        background: "rgba(0,0,0,0.92)", display: "flex",
        alignItems: "center", justifyContent: "center",
      }}
    >
      <button
        onClick={onClose}
        style={{
          position: "absolute", top: 20, right: 24,
          background: "rgba(255,255,255,0.1)", border: "1px solid rgba(255,255,255,0.2)",
          color: "#fff", borderRadius: "50%", width: 40, height: 40,
          fontSize: "1.2rem", cursor: "pointer", lineHeight: 1,
        }}
      >✕</button>
      <img
        src={src}
        alt="AI redesign fullscreen"
        onClick={(e) => e.stopPropagation()}
        style={{ maxWidth: "95vw", maxHeight: "92vh", objectFit: "contain", borderRadius: 8, boxShadow: "0 0 60px rgba(0,0,0,0.8)" }}
      />
    </div>
  );
}

export default function ResultsTabs({ design, style, room, budget, onGenerateImage, generatedImageUrl, generatingImage }) {
  const [tab, setTab] = useState(0);
  const [lightbox, setLightbox] = useState(false);
  if (!design) return null;

  const { headline, overview, vastu_tip, colors = [], walls, flooring, ceiling, lighting,
    furniture = [], layout_tips = [], decor, costs = {}, shopping = [], pro_tips = [] } = design;

  const copyPlan = () => {
    const text = `DecorGenie AI Design Plan\n\n${headline}\n${style} ${room} · ${budget}\n\n${overview}\n\nVastu: ${vastu_tip}\n\nEstimated Total: ${costs.total || "—"}\n\nGenerated by DecorGenie AI · decorgenie.ai`;
    navigator.clipboard.writeText(text);
    toast.success("Design plan copied!");
  };

  const shareLink = () => {
    navigator.clipboard.writeText(window.location.href);
    toast.success("Link copied! Save feature requires an account.");
  };

  return (
    <div style={{ marginTop: "1.25rem" }}>
      {/* Headline */}
      <div style={{ marginBottom: "1rem" }}>
        <div style={{ fontFamily: "'Cormorant Garamond', serif", fontSize: "1.3rem", color: "#D4A84B" }}>{headline}</div>
        <div style={{ fontSize: "0.8rem", color: "#6B5E4E", marginTop: "0.15rem" }}>{style} · {room} · {budget}</div>
      </div>

      {/* Vastu tip */}
      {vastu_tip && (
        <div style={{ background: "rgba(61,122,82,0.12)", border: "1px solid rgba(61,122,82,0.3)", borderRadius: "8px", padding: "0.7rem 1rem", fontSize: "0.84rem", color: "#7DCB97", marginBottom: "1rem", lineHeight: 1.5 }}>
          🧿 <strong>Vastu:</strong> {vastu_tip}
        </div>
      )}

      {/* Tab bar */}
      <div style={{ display: "flex", borderBottom: "1px solid rgba(212,168,75,0.12)", marginBottom: "1.25rem", overflowX: "auto" }}>
        {TABS.map((t, i) => (
          <button key={t} onClick={() => setTab(i)} style={{
            padding: "0.55rem 1rem", fontSize: "0.8rem", fontWeight: 500, cursor: "pointer",
            background: "none", border: "none", fontFamily: "'Outfit', sans-serif",
            color: tab === i ? "#D4A84B" : "#6B5E4E",
            borderBottom: tab === i ? "2px solid #D4A84B" : "2px solid transparent",
            whiteSpace: "nowrap", transition: "all 0.15s",
          }}>{t}</button>
        ))}
      </div>

      {/* TAB 0: Concept */}
      {tab === 0 && (
        <div>
          <DCard title="Vision"><p style={{ fontSize: "0.88rem", color: "#F0EBE1", lineHeight: 1.65 }}>{overview}</p></DCard>
          <div style={{ margin: "1rem 0" }}>
            <div style={{ fontSize: "0.68rem", fontWeight: 600, textTransform: "uppercase", letterSpacing: "0.07em", color: "#6B5E4E", marginBottom: "0.6rem" }}>Color Palette</div>
            {colors.map((c, i) => (
              <div key={i} style={{ display: "flex", alignItems: "center", gap: "0.75rem", padding: "0.5rem 0", borderBottom: "1px solid rgba(212,168,75,0.08)" }}>
                <div style={{ width: 40, height: 40, borderRadius: 8, background: c.hex, border: "1px solid rgba(255,255,255,0.08)", flexShrink: 0 }} />
                <div>
                  <div style={{ fontSize: "0.83rem", fontWeight: 500, color: "#F0EBE1" }}>{c.name} <span style={{ fontSize: "0.72rem", color: "#6B5E4E" }}>{c.hex}</span></div>
                  <div style={{ fontSize: "0.75rem", color: "#A89880" }}>{c.use}</div>
                </div>
              </div>
            ))}
          </div>
          <DCard title="Decor & Accessories"><p style={{ fontSize: "0.88rem", color: "#F0EBE1", lineHeight: 1.65 }}>{decor}</p></DCard>

          {/* AI Image */}
          {lightbox && <Lightbox src={generatedImageUrl} onClose={() => setLightbox(false)} />}
          <div style={{ marginTop: "1rem", background: "#272320", border: "1px solid rgba(212,168,75,0.12)", borderRadius: "12px", overflow: "hidden" }}>
            {generatedImageUrl ? (
              <div style={{ position: "relative", cursor: "zoom-in" }} onClick={() => setLightbox(true)}>
                <img src={generatedImageUrl} alt="AI redesign" style={{ width: "100%", display: "block", maxHeight: 280, objectFit: "cover" }} />
                <div style={{
                  position: "absolute", top: 8, right: 8,
                  background: "rgba(0,0,0,0.55)", border: "1px solid rgba(255,255,255,0.2)",
                  borderRadius: 6, padding: "0.25rem 0.5rem", fontSize: "0.72rem", color: "#fff",
                  pointerEvents: "none",
                }}>⛶ Fullscreen</div>
              </div>
            ) : (
              <div style={{ padding: "1.5rem", textAlign: "center" }}>
                <div style={{ fontSize: "1.5rem", opacity: 0.3, marginBottom: "0.5rem" }}>🖼️</div>
                <div style={{ fontSize: "0.83rem", color: "#A89880", marginBottom: "0.75rem" }}>Generate a photorealistic render of this design</div>
                <button onClick={onGenerateImage} disabled={generatingImage} style={{
                  background: generatingImage ? "rgba(212,168,75,0.3)" : "#D4A84B", color: "#0D0B08",
                  border: "none", borderRadius: "8px", padding: "0.55rem 1.25rem",
                  fontSize: "0.82rem", fontWeight: 700, cursor: generatingImage ? "not-allowed" : "pointer",
                  fontFamily: "'Outfit', sans-serif",
                }}>
                  {generatingImage ? "⏳ Rendering…" : "✦ Generate Room Image"}
                </button>
                <div style={{ fontSize: "0.7rem", color: "#6B5E4E", marginTop: "0.5rem" }}>Requires Stability AI or Replicate API key</div>
              </div>
            )}
          </div>
        </div>
      )}

      {/* TAB 1: Materials */}
      {tab === 1 && (
        <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "0.75rem" }}>
          <DCard title="🎨 Walls"><p style={{ fontSize: "0.85rem", color: "#F0EBE1", lineHeight: 1.6 }}>{walls}</p></DCard>
          <DCard title="🪵 Flooring"><p style={{ fontSize: "0.85rem", color: "#F0EBE1", lineHeight: 1.6 }}>{flooring}</p></DCard>
          <DCard title="✨ Ceiling"><p style={{ fontSize: "0.85rem", color: "#F0EBE1", lineHeight: 1.6 }}>{ceiling}</p></DCard>
          <DCard title="💡 Lighting"><p style={{ fontSize: "0.85rem", color: "#F0EBE1", lineHeight: 1.6 }}>{lighting}</p></DCard>
        </div>
      )}

      {/* TAB 2: Furniture */}
      {tab === 2 && (
        <div>
          <DCard title="Recommended Furniture">
            <ul style={{ listStyle: "none" }}>
              {furniture.map((f, i) => (
                <li key={i} style={{ display: "flex", gap: "0.5rem", padding: "0.45rem 0", borderBottom: "1px solid rgba(212,168,75,0.08)", fontSize: "0.87rem", color: "#F0EBE1", lineHeight: 1.5 }}>
                  <span style={{ color: "#D4A84B", fontWeight: 700 }}>→</span>{f}
                </li>
              ))}
            </ul>
          </DCard>
          <div style={{ marginTop: "0.75rem" }}>
            <DCard title="Layout Tips">
              <ul style={{ listStyle: "none" }}>
                {layout_tips.map((t, i) => (
                  <li key={i} style={{ display: "flex", gap: "0.5rem", padding: "0.4rem 0", fontSize: "0.87rem", color: "#F0EBE1", lineHeight: 1.5 }}>
                    <span style={{ color: "#D4A84B", fontSize: "0.65rem", marginTop: "0.35rem" }}>✦</span>{t}
                  </li>
                ))}
              </ul>
            </DCard>
          </div>
          <div style={{ marginTop: "0.75rem" }}>
            <DCard title="Pro Designer Tips">
              <ul style={{ listStyle: "none" }}>
                {pro_tips.map((t, i) => (
                  <li key={i} style={{ display: "flex", gap: "0.5rem", padding: "0.4rem 0", fontSize: "0.87rem", color: "#F0EBE1", lineHeight: 1.5 }}>
                    <span style={{ color: "#D4A84B", fontSize: "0.65rem", marginTop: "0.35rem" }}>◎</span>{t}
                  </li>
                ))}
              </ul>
            </DCard>
          </div>
        </div>
      )}

      {/* TAB 3: Budget */}
      {tab === 3 && (
        <DCard title={`Renovation Estimate — ${budget}`}>
          <table style={{ width: "100%", borderCollapse: "collapse" }}>
            <tbody>
              {[
                ["🎨 Painting & Walls", costs.painting],
                ["🪵 Flooring", costs.flooring],
                ["🛋️ Furniture", costs.furniture],
                ["💡 Lighting", costs.lighting],
                ["✨ False Ceiling / POP", costs.false_ceiling],
              ].map(([label, val]) => val && (
                <tr key={label} style={{ borderBottom: "1px solid rgba(212,168,75,0.08)" }}>
                  <td style={{ padding: "0.55rem 0.3rem", fontSize: "0.86rem", color: "#A89880" }}>{label}</td>
                  <td style={{ padding: "0.55rem 0.3rem", fontSize: "0.86rem", color: "#E8C97A", fontWeight: 500, textAlign: "right" }}>{val}</td>
                </tr>
              ))}
              <tr style={{ background: "rgba(212,168,75,0.06)" }}>
                <td style={{ padding: "0.75rem 0.3rem", fontSize: "0.95rem", fontWeight: 700, color: "#D4A84B" }}>Total Estimate</td>
                <td style={{ padding: "0.75rem 0.3rem", fontSize: "0.95rem", fontWeight: 700, color: "#D4A84B", textAlign: "right" }}>{costs.total}</td>
              </tr>
            </tbody>
          </table>
          <p style={{ fontSize: "0.72rem", color: "#6B5E4E", marginTop: "0.75rem", lineHeight: 1.5 }}>
            * Approximate costs for Indian Tier-1/2 cities. Final prices vary by contractor and location.
          </p>
        </DCard>
      )}

      {/* TAB 4: Shop */}
      {tab === 4 && (
        <div>
          <div style={{ fontSize: "0.8rem", color: "#A89880", marginBottom: "0.75rem" }}>Curated picks for your {style} {room}</div>
          <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(150px, 1fr))", gap: "0.75rem" }}>
            {shopping.map((item, i) => (
              <div key={i} onClick={() => toast("🛍️ Shopping links coming with affiliate integration!")}
                style={{ background: "#1E1B16", border: "1px solid rgba(212,168,75,0.12)", borderRadius: "12px", overflow: "hidden", cursor: "pointer", transition: "all 0.2s" }}
                onMouseEnter={(e) => e.currentTarget.style.borderColor = "rgba(212,168,75,0.4)"}
                onMouseLeave={(e) => e.currentTarget.style.borderColor = "rgba(212,168,75,0.12)"}
              >
                <div style={{ background: "#272320", height: 100, display: "flex", alignItems: "center", justifyContent: "center", fontSize: "2.5rem" }}>{item.emoji}</div>
                <div style={{ padding: "0.6rem 0.7rem" }}>
                  <div style={{ fontSize: "0.8rem", fontWeight: 500, color: "#F0EBE1", marginBottom: "0.2rem" }}>{item.name}</div>
                  <div style={{ fontSize: "0.75rem", color: "#D4A84B" }}>{item.price}</div>
                  <div style={{ fontSize: "0.68rem", color: "#6B5E4E" }}>{item.style} · {item.store}</div>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Action row */}
      <div style={{ display: "flex", gap: "0.5rem", marginTop: "1.25rem", flexWrap: "wrap" }}>
        {[
          { label: "📋 Copy Plan", fn: copyPlan },
          { label: "🔗 Share", fn: shareLink },
          { label: "📱 AR View", fn: () => toast("AR Preview — install the DecorGenie app!") },
        ].map(({ label, fn }) => (
          <button key={label} onClick={fn} style={{
            flex: 1, minWidth: 90, padding: "0.5rem 0.5rem",
            border: "1px solid rgba(212,168,75,0.18)", borderRadius: "8px",
            background: "#1E1B16", color: "#A89880", fontSize: "0.78rem",
            cursor: "pointer", fontFamily: "'Outfit', sans-serif", transition: "all 0.15s",
          }}
            onMouseEnter={(e) => { e.currentTarget.style.borderColor = "#D4A84B"; e.currentTarget.style.color = "#D4A84B"; }}
            onMouseLeave={(e) => { e.currentTarget.style.borderColor = "rgba(212,168,75,0.18)"; e.currentTarget.style.color = "#A89880"; }}
          >{label}</button>
        ))}
      </div>
    </div>
  );
}

function DCard({ title, children }) {
  return (
    <div style={{ background: "#1E1B16", border: "1px solid rgba(212,168,75,0.1)", borderRadius: "12px", padding: "1rem" }}>
      <div style={{ fontSize: "0.68rem", fontWeight: 600, textTransform: "uppercase", letterSpacing: "0.07em", color: "#6B5E4E", marginBottom: "0.5rem" }}>{title}</div>
      {children}
    </div>
  );
}
